# Generated by Django 3.1.7 on 2021-04-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SynthPatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.FilePathField(max_length=200)),
                ('synth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.synth')),
            ],
        ),
        migrations.CreateModel(
            name='UmapMFCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_1', models.FloatField(blank=True, null=True)),
                ('dim_2', models.FloatField(blank=True, null=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.synthpatch')),
            ],
        ),
    ]
