# Generated by Django 3.1.7 on 2021-04-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_spectralfeatures_umapspectral'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthpatch',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
