# Generated by Django 5.0.2 on 2024-02-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0004_synthpatch_pitch"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextFeatures",
            fields=[
                (
                    "patch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="browser.synthpatch",
                    ),
                ),
                ("percussive", models.FloatField(blank=True, null=True)),
                ("metallic", models.FloatField(blank=True, null=True)),
                ("sharp", models.FloatField(blank=True, null=True)),
                ("bright", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
